version: '3.8'

services:
  streamlit_app:
    build: .
    container_name: streamlit_rag_app
    ports:
      - "8501:8501"
    networks:
      - shared_rag_network
    environment:
      - OPENAI_API_KEY=your_openai_api_key  # Replace with your actual key if using OpenAI
      - PRODUCT_EVENTS_API_URL=http://product_events_api:8000  # Replace with the actual URL if different
networks:
  shared_rag_network:
    external: true